application:
  name: tides

elasticsearch:
  cluster: elasticsearch
  host: localhost
  port: 9300
  indexName: tides
  
logging:
    level:
        es.tidetim: DEBUG
        org.springframework: INFO

