application:
  name: tides

elasticsearch:
  cluster: crystalmark
  manipulationAllowed: true
  servers:
    - host: localhost
      port: 9300

logging:
    level:
        es.tidetim: DEBUG
        org.springframework: INFO

