application:
  name: tides

server:
    port: 8089

elasticsearch:
  cluster: mygovscot
  host: localhost
  port: 9300
  indexName: tides
  
logging:
    level:
        es.tidetim: DEBUG
        org.springframework: INFO

